name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
    - family: VarelaRound
      fonts:
        - asset: google_fonts/Varela_Round/VarelaRound-Regular.ttf
    - family: Oswald
      fonts:
        - asset: google_fonts/Oswald/Oswald-VariableFont:wght.ttf
    - family: PermanentMarker
      fonts:
        - asset: google_fonts/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: CreteRound
      fonts:
        - asset: google_fonts/Crete_Round/CreteRound-Regular.ttf
    - family: Rajdhani
      fonts:
        - asset: google_fonts/Rajdhani/Rajdhani-Bold.ttf
    - family: Poppins
      fonts:
        - asset: google_fonts/Poppins/Poppins-Bold.ttf
